tricore-t-yui/ev-mock

pro_builder_test/Assets/KazuoFile.meta, pro_builder_test/Assets/KazuoFile/CameraController.cs, pro_builder_test/Assets/KazuoFile/CameraController.cs.meta, pro_builder_test/Assets/KazuoFile/KazuoScene.unity, pro_builder_test/Assets/KazuoFile/KazuoScene.unity.meta, pro_builder_test/Assets/KazuoFile/PlayerBrethController.cs, pro_builder_test/Assets/KazuoFile/PlayerBrethController.cs.meta, pro_builder_test/Assets/KazuoFile/PlayerMoveController.cs, pro_builder_test/Assets/KazuoFile/PlayerMoveController.cs.meta, pro_builder_test/Assets/KazuoFile/PlayerMover.cs, pro_builder_test/Assets/KazuoFile/PlayerMover.cs.meta
=> プレイヤーの動き、息クラス作成

pro_builder_test/Assets/Mitsumaru.meta, pro_builder_test/Assets/Mitsumaru/Materials.meta, pro_builder_test/Assets/Mitsumaru/Materials/EnemyMat.mat, pro_builder_test/Assets/Mitsumaru/Materials/EnemyMat.mat.meta, pro_builder_test/Assets/Mitsumaru/Materials/PlayerMat.mat, pro_builder_test/Assets/Mitsumaru/Materials/PlayerMat.mat.meta, pro_builder_test/Assets/Mitsumaru/Scripts.meta, pro_builder_test/Assets/Mitsumaru/Scripts/EnemyMover.cs, pro_builder_test/Assets/Mitsumaru/Scripts/EnemyMover.cs.meta, pro_builder_test/Assets/Mitsumaru/TestScene_Mitsumaru.meta, pro_builder_test/Assets/Mitsumaru/TestScene_Mitsumaru.unity, pro_builder_test/Assets/Mitsumaru/TestScene_Mitsumaru.unity.meta, pro_builder_test/Assets/Mitsumaru/TestScene_Mitsumaru/NavMesh.asset, pro_builder_test/Assets/Mitsumaru/TestScene_Mitsumaru/NavMesh.asset.meta
決められたルートを移動し続ける処理を作成した。
リストに複数の目標位置を設定して、順番に移動していく感じ。
【確認ファイル】
EnemyMove.cs
=> エネミーの徘徊処理を作成

pro_builder_test/Assets/Mitsumaru/Scripts/EnemyChaser.cs, pro_builder_test/Assets/Mitsumaru/Scripts/EnemyChaser.cs.meta, pro_builder_test/Assets/Mitsumaru/TestScene_Mitsumaru.unity
エネミーがプレイヤーを発見したときに追跡する処理を作成した。
スクリプトではプレイヤーの位置を毎フレーム入れてるだけ。
【確認ファイル】
EnemyChaser.cs
=> エネミーがププレイヤーを追跡する処理を作成

pro_builder_test/Assets/KazuoFile/Animation.meta, pro_builder_test/Assets/KazuoFile/Animation/BrethGageBlink.anim, pro_builder_test/Assets/KazuoFile/Animation/BrethGageBlink.anim.meta, pro_builder_test/Assets/KazuoFile/Animation/Gage.controller, pro_builder_test/Assets/KazuoFile/Animation/Gage.controller.meta, pro_builder_test/Assets/KazuoFile/Animation/HealthGageBlink.anim, pro_builder_test/Assets/KazuoFile/Animation/HealthGageBlink.anim.meta, pro_builder_test/Assets/KazuoFile/Prefab.meta, pro_builder_test/Assets/KazuoFile/Script.meta
ゲージがある程度の割合を下回った時と、息切れ時にゲージを点滅させるためのアニメーション追加
=> ゲージ点滅アニメーション追加

pro_builder_test/Assets/KazuoFile/KazuoScene.unity, pro_builder_test/Assets/KazuoFile/Player.prefab, pro_builder_test/Assets/KazuoFile/PlayerBrethController.cs, pro_builder_test/Assets/KazuoFile/PlayerMoveController.cs, pro_builder_test/Assets/KazuoFile/PlayerMover.cs
隠れている時に近くに敵がいたら息を消費するように修正し、
プレイヤー関連のコードを少しだけ見やすくしました。
=> 隠れている時に近くに敵がいたら息を消費するように修正

pro_builder_test/Assets/Mitsumaru/Scripts/WarningAreaEnterChecker.cs, pro_builder_test/Assets/Mitsumaru/Scripts/WarningAreaEnterChecker.cs.meta, pro_builder_test/Assets/Mitsumaru/TestScene_Mitsumaru.unity
敵が警戒ゾーンに移行する範囲に入ったかどうかを判定するクラスを作成した。
入ったかどうかのフラグと入ったオブジェクトの名前を返す。
【確認ファイル】
WarningAreaEnterChecker.cs
=> 警戒ゾーンのコライダーに入ったかどうか判定する処理を作成

pro_builder_test/Assets/KazuoFile/KazuoScene.unity, pro_builder_test/Assets/KazuoFile/Script/PlayerBrethController.cs, pro_builder_test/Assets/KazuoFile/Script/PlayerMoveController.cs, pro_builder_test/Assets/KazuoFile/Script/PlayerMover.cs, pro_builder_test/Assets/KazuoFile/Script/SliderController.cs
段差を登れるように追記しました。
デフォルト値をある程度入れておいたらスクリプトをつけた時に楽かと思ったので入力しました。
=> 段差を登れるように追記、各変数のデフォルト値入力

pro_builder_test/Assets/KazuoFile/Script/PlayerBrethController.cs
=> 息切れ時に息を低速で回復させるように修正

pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Animation/Enemy.controller, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/EnemyReturnPointList.cs, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/State/EnemySearch.cs, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/TestScene_Mitsumaru.unity
プレイヤーを見失って、指定のポイントまで移動する処理でプレイヤーではなく敵に一番近いポイントに移動するようになっていたので、プレイヤーに一番近いポイントまで移動するように修正した。
【確認ファイル】
EnemyReturnPointList.cs
EnemySearch.cs
=> 処理の内容が間違っていたので修正

pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Enemy/EnemyParameterIdList.cs, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Enemy/EnemyParameterIdList.cs.meta
敵のパラメータからハッシュ値を生成してキーと一緒に管理する。
このクラスを介してパラメータにアクセスする。
【確認ファイル】
EnemyParameterIdList.cs
=> 敵のパラメータをハッシュ値で管理するクラスを作成

pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/Bed.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/Bed.prefab.meta, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/InteractController.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/InteractController.prefab.meta, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/Locker.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/Locker.prefab.meta, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/CameraController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/DoorController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/InteractController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/InteractController.cs.meta, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/PlayerDoorController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/PlayerEvents.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/DashDoorOpenState.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/DoorOpenState.cs
プレハブ追加し、主にドアや隠れるなどの処理のコードを修正しました。
=> プレハブ追加、コード修正

pro_builder_test/Assets/ProgrammerSample/Mitsumaru/ImportAssets/unity-chan!/Unity-chan! Model/Art/Animations.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/ImportAssets/unity-chan!/Unity-chan! Model/Art/Animations/Animators.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/ImportAssets/unity-chan!/Unity-chan! Model/Art/Animations/FaceAnimation.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/ImportAssets/unity-chan!/Unity-chan! Model/Art/Stage/Materials.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/ImportAssets/unity-chan!/Unity-chan! Model/Art/Stage/Shader.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/ImportAssets/unity-chan!/Unity-chan! Model/Art/Stage/Shader/Textures.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/ImportAssets/unity-chan!/Unity-chan! Model/Art/Stage/Textures.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/ImportAssets/unity-chan!/Unity-chan! Model/Art/UnityChanShader.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/ImportAssets/unity-chan!/Unity-chan! Model/Art/UnityChanShader/Materials.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/ImportAssets/unity-chan!/Unity-chan! Model/Art/UnityChanShader/Shader.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/ImportAssets/unity-chan!/Unity-chan! Model/Art/UnityChanShader/Texture.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Enemy/EnemyVisibility.cs, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Other/ColliderEvent.cs, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Other/ColliderEvent.cs.meta
コライダーに衝突したときにUnityEventに登録されたイベントを実行する汎用クラスを作成した。
Enter,Stay,Exit,のそれぞれ３つのUnityEventを用意している。
【確認ファイル】
ColliderEvent.cs
=> コライダー専用のUnityEventの汎用クラスを作成

pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Enemy/EnemyVisibility.cs
=> 敵の視界のベクトルの計算が間違っていたので修正

pro_builder_test/Assets/ProgrammerSample/KazuoFile/Animation/Door/Door.controller, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Animation/Hide/Locker.controller, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Animation/Player/BedInWait.anim, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Animation/Player/BedInWait.anim.meta, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Animation/Player/Player.controller, pro_builder_test/Assets/ProgrammerSample/KazuoFile/KazuoScene.unity, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Camera/CameraController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerBrethController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerHideController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/InteractObject/Door/DashDoorOpenState.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/InteractObject/Door/DoorOpenState.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/InteractObject/Hide/HideObjectInState.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/InteractObject/Hide/HideObjectOutState.cs, pro_builder_test/ProjectSettings/TagManager.asset
=> 隠れた時に視点移動ができるように修正

pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/InteractObject/Hide/HideObjectOutState.cs
=> 回転したまんまなので真正面に向くよう修正

pro_builder_test/Assets/ProgrammerSample/KazuoFile/Animation/Player/Player.controller, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/InteractObject/Hide/HideObjectOutState.cs
隠れるのをやめた時、瞬時に向くのではなく、ゆっくりベッドやロッカーの脱出方向を向くように修正しました
=> 隠れるのをやめた時、ベッドやロッカーの脱出方向を向くように修正

pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Stage/AreaEnterWatcher.cs, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Stage/AreaManager.cs, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/TestScene_Mitsumaru.unity
コードミスによりエリアの情報を正しく取得できていなかったので修正した。
【確認ファイル】
AreaEnterWatcher.cs
AreaManager.cs
=> エリア管理の処理の不具合修正

pro_builder_test/Assets/ProgrammerSample/KazuoFile/Animation/Door/Close.anim, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Animation/Door/DashOpen.anim, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Animation/Door/Open.anim, pro_builder_test/Assets/ProgrammerSample/KazuoFile/KazuoScene.unity, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/Door.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Camera/CameraController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/InteractObject/Door/DoorController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/InteractObject/Hide/HideObjectController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerHideController.cs
カメラの上下の視点移動に制限をつけたのと、
隠れるアクション関連のコード修正を行いました
=> カメラの上下制限、コード修正

pro_builder_test/Assets/ProgrammerSample/KazuoFile/Animation/Player/Player.controller, pro_builder_test/Assets/ProgrammerSample/KazuoFile/KazuoScene.unity, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/Controller/InteractController.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/Controller/PlayerEventController.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/Controller/PlayerStateController.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/Player.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/PlayerCameraParent.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/PlayerCameraParent.prefab.meta, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Camera/CameraController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerDamageController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerDoorController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerEvents.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerHealthController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerHideController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/DamageEndState.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/DamageEndState.cs.meta, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/DeathState.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/DeathState.cs.meta, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/PlayerStateController.cs
=> ダメージ処理関連のコード修正

pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Enemy/State/KageStateNormal.cs, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Enemy/State/KageStateNormal.cs.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Enemy/State/KageStateStanding.cs, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Enemy/State/KageStateStanding.cs.meta
【確認ファイル】
KageStateNormal.cs
KageStateStanding.cs
=> 影人間の通常状態時の動作で「待機型」か「徘徊型」かを選択する処理を作成

pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Enemy/State/KageStateMoveAtRoute.cs, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Enemy/State/KageStateMoveAtRoute.cs.meta
【確認ファイル】
KageStateMveAtRoute.cs
=> 影人間のルートによる徘徊処理を作成

pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Enemy/State/KageLoiteringOtherAction.cs, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Enemy/State/KageLoiteringOtherAction.cs.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Enemy/State/KageLotteryNextBehavior.cs, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Enemy/State/KageLotteryNextBehavior.cs.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Enemy/State/KageStateLoitering.cs, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Enemy/State/KageStateLoitering.cs.meta
【確認ファイル】
KageLotteryOtherAction.cs
KageLotteryNextBehavior.cs
KageStateLoitering.cs
=> 影人間の徘徊時にその他の行動に切り替える処理を作成

pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Enemy/State/OtherActionDanceWildly.cs, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Enemy/State/OtherActionDanceWildly.cs.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Enemy/State/OtherActionFallDownAndGetUp.cs, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Enemy/State/OtherActionFallDownAndGetUp.cs.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Enemy/State/OtherActionRunning.cs, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Enemy/State/OtherActionRunning.cs.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Enemy/State/OtherActionSingWhileWalking.cs, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Enemy/State/OtherActionSingWhileWalking.cs.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Enemy/State/OtherActionStopAndCry.cs, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Enemy/State/OtherActionStopAndCry.cs.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Enemy/State/OtherActionStopAndLookAround.cs, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Enemy/State/OtherActionStopAndLookAround.cs.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Enemy/State/OtherActionTalking.cs, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Enemy/State/OtherActionTalking.cs.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Enemy/State/OtherActionVibrationBody.cs, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Enemy/State/OtherActionVibrationBody.cs.meta
=> 影人間の徘徊時の「その他の行動」のスクリプトを作成

pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Animation.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Animation/Kage.controller, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Animation/Kage.controller.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Animation/Z_Attack.anim, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Animation/Z_Attack.anim.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Materials.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Materials/EnemyMat.mat.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Materials/PlayerMat.mat.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Prefabs.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/DebugOnly.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/DebugOnly/EnemyRouteDrawer.cs, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/DebugOnly/EnemyRouteDrawer.cs.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Enemy.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Other.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Other/ColliderEvent.cs.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Other/PlayerMoverTest.cs.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Other/StateMachine.cs.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Stage.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Stage/AreaEnterWatcher.cs.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Stage/AreaManager.cs.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/TestScene_Mitsumaru.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/TestScene_Mitsumaru.unity, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/TestScene_Mitsumaru.unity.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/TestScene_Mitsumaru/NavMesh.asset.meta
=> その他メタファイルをコミット

pro_builder_test/Assets/ProgrammerSample/KazuoFile/Animation/Player/Player.controller, pro_builder_test/Assets/ProgrammerSample/KazuoFile/KazuoScene.unity, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/PlayerCameraParent.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Camera/CameraController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Gage/ScreenEffectController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerDamageController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/Player/PlayerStateController.cs
ゲームオーバー演出追加しました。
まだ敵のトドメに応じたゲームオーバー演出は作っていません
=> ゲームオーバー演出追加

pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Animation/Kage.controller, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Enemy/KageAnimParameterList.cs, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/TestScene_Mitsumaru.unity
ステートの項目を追加しただけなので中身は空。
シーン上にルート徘徊、ランダム徘徊、待機型の影人間をそれぞれ追加した。
=> Animatorに警戒状態時のステートを追加

pro_builder_test/Assets/ProgrammerSample/KazuoFile/Animation/Player/Player.controller, pro_builder_test/Assets/ProgrammerSample/KazuoFile/KazuoScene.unity, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/EffectCanvas.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Gage/ScreenEffectController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/InteractObject/Hide/HideObjectController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerDoorController.cs, pro_builder_test/Assets/ProgrammerSample/SampleScene.unity
=> プログラマーシーンに修正後のプレハブ配置

pro_builder_test/Assets/ProgrammerSample/KazuoFile/Animation/Hide/Locker.controller, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Animation/Player/Barefoot.anim, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Animation/Player/BarefootEnd.anim, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Animation/Player/BrethlessnessEnd.anim, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Animation/Player/Player.controller, pro_builder_test/Assets/ProgrammerSample/KazuoFile/KazuoScene.unity, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/Player.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/PlayerCameraParent.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Camera/CameraController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerAnimationContoller.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerEvents.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/Player/BarefootEndState.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/Player/BarefootStartState.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/Player/BedStealthState.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/Player/LockerLoopState.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/Player/LockerStealthState.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/Player/PlayerStateController.cs
=> 右手の表示非表示切り替え

pro_builder_test/Assets/ProgrammerSample/KazuoFile/Animation/Player/Barefoot.anim, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Animation/Player/BarefootEnd.anim, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Animation/Player/LockerIn.anim, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Animation/Player/LockerOut.anim, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Animation/Player/Player.controller, pro_builder_test/Assets/ProgrammerSample/KazuoFile/KazuoScene.unity, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/Controller/PlayerEventController.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/Controller/PlayerStateController.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/ControllerObject.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/Door.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/Locker.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/Player.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/InteractObject/Door/DoorController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/InteractObject/InteractFunction.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerAnimationContoller.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerDamageController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerDoorController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerEvents.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerHealthController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerHideController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/InteractObject/Door/DoorOpenState.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/Player/BarefootEndState.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/Player/BarefootStartState.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/Player/PlayerStateController.cs
ダメージを食らった時のアニメーション中断を実装しました。
ついでにロッカーと靴脱ぎのアニメーションをすこし修正しました。
=> ダメージを食らった時のアニメーション中断

pro_builder_test/Assets/ProgrammerSample/KazuoFile/Animation/Player/StandUp.anim, pro_builder_test/Assets/ProgrammerSample/KazuoFile/KazuoScene.unity, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/InteractObject/Door/DoorController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerDamageController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerEvents.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerMoveController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/Player/PlayerStateController.cs, pro_builder_test/ProjectSettings/TagManager.asset
移動速度の上限変更が正しく行われていなかったので移動系コード修正したのと、
離れたら勝手にドアが閉まるように修正しました
=> 移動系コード、ドア修正

pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerBreathController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerEvents.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerObjectDamageController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/SoundAreaSpawner.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/Player/BedStealthState.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/Player/LockerStealthState.cs
=> アニメーション、音関係修正

pro_builder_test/Assets/ProgrammerSample/KazuoFile/Animation/Player/DashDoorOpen.anim, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Animation/Player/Player.controller, pro_builder_test/Assets/ProgrammerSample/KazuoFile/KazuoScene.unity, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerEvents.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerMoveController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/SoundAreaSpawner.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/Player/HideStateController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/Player/PlayerStateController.cs
=> 隠れているときの状態処理更新

pro_builder_test/Assets/Bakery/ftGlobalStorage.asset, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Animation/Player/Player.controller, pro_builder_test/Assets/ProgrammerSample/KazuoFile/KazuoScene.unity, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/Bed.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/Controller/InteractController.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/Controller/PlayerEventController.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/Controller/PlayerStateController.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/ControllerObject.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/Locker.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/Player.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/SoundAreaSpawner.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Camera/CameraController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/InteractObject/Hide/HideObjectController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/InteractObject/InteractFunction.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerAnimationContoller.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerDamageController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerEventCaller.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerEvents.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerHideController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerMoveController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/SoundAreaController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/Player/PlayerStateController.cs
音領域の大きさによって領域の減少量を変更するよう修正しました
=> 音領域の大きさによって領域の減少量を変更するよう修正

pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Camera/CameraAnimationController.cs
=> カメラアニメーションクラス修正

pro_builder_test/Assets/ProgrammerSample/KazuoFile/Animation/Door/Door.controller, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Animation/Player/BedIn.anim, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Animation/Player/Player.controller, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerBreathController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/SoundAreaSpawner.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/Player/BedLoopState.cs, pro_builder_test/Assets/ProgrammerSample/SampleScene.unity
=> アニメーション、息消費調整

pro_builder_test/Assets/ProgrammerSample/KazuoFile/Animation/Camera/DeepBreath.anim, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Animation/Player/Player.controller, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/Bed.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/Locker.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Camera/CameraAnimationController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerEvents.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerObjectDamageController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerStatusController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/InteractObject/Hide/BedInState.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/Player/BedLoopState.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/Player/BedStealthState.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/Player/LockerLoopState.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/Player/LockerStealthState.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/Player/PlayerStateController.cs, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Animation/Kage.controller, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Kage.meta, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Stage/AreaManager.cs, pro_builder_test/Assets/ProgrammerSample/SampleScene.unity, pro_builder_test/Assets/ProgrammerSample/SampleScene/NavMesh.asset, pro_builder_test/ProjectSettings/TagManager.asset
=> マップ、息関連コード修正

pro_builder_test/Assets/ProgrammerSample/KazuoFile/Animation/Hide/Locker.controller, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/Bed.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/Controller/PlayerEvents.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/Controller/PlayerStateController.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/ControllerObject.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/Doll.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/Door.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Prefab/PlayerObject.prefab, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Camera/CameraController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/InteractObject/Door/DoorController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/InteractObject/Hide/HideObjectController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/KeyController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerBreathController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerDoorController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerEvents.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerHideController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerMoveController.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/InteractObject/Door/DoorOpenState.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/InteractObject/Hide/LockerInState.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/Player/BedLoopState.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/Player/BedStealthState.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/Player/LockerLoopState.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/Player/LockerStealthState.cs, pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/State/Player/PlayerStateController.cs, pro_builder_test/Assets/ProgrammerSample/SampleScene.unity, pro_builder_test/ProjectSettings/InputManager.asset
=> 土曜の指摘箇所修正、コントローラー対応

pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Kage/State/KageStatePlayerChaser.cs
=> 影人間がプレイヤーの方に向ききれず攻撃に移行できない可能性を修正

pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/GameController.cs, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Animation/Kage.controller, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/KageManager.cs, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Prefabs/Kage.prefab, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Kage/State/EnemyTransformSetter.cs, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Kage/State/KageStatePlayerChaser.cs, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Kage/State/KageStateReturnLoiteringPoint.cs, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Kage/State/KageStateReturnStandingPoint.cs, pro_builder_test/Assets/Rewired/Plugins/NintendoSwitch/Integration.meta
・追跡を終了しても指定の位置に戻らない。
・追跡中に目標位置に到着しても警戒に移行してくれない。
・一部の影人間の初期化ができていなかった。
=> 影人間の不具合をいくつか修正

pro_builder_test/Assets/ProgrammerSample/KazuoFile/Script/Player/PlayerHideController.cs, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Animation/Kage.controller, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Animation/Oni.controller, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Animation/Tun.controller, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Kage/KageAnimParameterList.cs, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Kage/State/KageStatePlayerChaser.cs, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Oni/OniStateApproachThePlayer.cs, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Tun/TunParameterChanger.cs, pro_builder_test/Assets/ProgrammerSample/Mitsumaru/Scripts/Tun/TunStateApproachHidePoint.cs, pro_builder_test/ProjectSettings/TagManager.asset
=> ダクトに隠れているときの攻撃処理を追加（動作未確認）
